### ISSUE TITLE
[Q] Clock card theme/colors

### ISSUE THREAD

**Issue by leikoilja** [Villhellm/lovelace-clock-card#11]
Hey, @Villhellm.
Thanks for the awesome clock card!

I was wondering what is the way to apply code colors/theme for the card? 
Mine currently looks like that by default. While the one if `README` you have looks so much better.
![image](https://user-images.githubusercontent.com/10655107/90395063-1f1d0a80-e094-11ea-9b96-d30a6c230f54.png)

Thanks

**Comment by Villhellm** [comment]
The colors are based on your currently selected theme. The background is `--primary-background-color`, the numbers are `--primary-text-color`, and the hands/border are `--accent-color`.

Though I have been contemplating making these manually configurable.

**Comment by leikoilja** [comment]
@Villhellm, thanks for the info. I would recommend introducing manual configuration and as a default falling on currently selected user's theme. 
Thing is that in my case for example, I use HACS frontend themes which changes the appearance independently of HA user theme. Also, in my particular use case your card perfectly fits tablet wall-mounted tablet dashboard. And over there it would be great just to configure colors manually and have no magic :smile: 
Thanks a lot

**Comment by Villhellm** [comment]
Custom theme options are now available in v0.4.0. Thanks for the suggestion!

**Comment by leikoilja** [comment]
Awesome! Thank you, @Villhellm for such a quick response
