### ISSUE TITLE
font_size not working

### ISSUE THREAD

**Issue by jankete** [Villhellm/lovelace-clock-card#18]
Hi, I tried to make the date a little smaller, but "font_size" doesn't seem to work. I tried the following without success:

font_size: 10
font_size: 10px
font_size: '10'
font_size: '10px'

**Comment by Villhellm** [comment]
Sorry, that was from a merged PR from a few months ago. I hadn't gotten around to making a new release yet. I just published v0.4.1 that will have the font_size option, all you have to do is update.

**Comment by jankete** [comment]
Thanks, now it workes.
