### ISSUE TITLE
feature request: city name under the clock

### ISSUE THREAD

**Issue by haddood** [Villhellm/lovelace-clock-card#3]
thank you for the beautiful card. it will be great if we can show name of the city under the clock and/or the country flag. Ideally, the name is automatic from the time zone. similar to https://www.timeanddate.com/worldclock/

**Comment by Villhellm** [comment]
Thanks for the suggestion! Added in the latest release.
I played around with adding the flag as well, but that turned out to be a rabbit hole that I didn't want to venture down at the moment. So for now it's just the text.

**Comment by Villhellm** [comment]
actually, give me a minute. I'm going to change the options a bit

**Comment by Villhellm** [comment]
okay, updated again. Now you can show the continent, city, or both.

**Comment by haddood** [comment]
wow ... that is fast reponse
