### ISSUE TITLE
Multiple Clocks on the same page

### ISSUE THREAD

**Issue by haddood** [Villhellm/lovelace-clock-card#4]
I added few clocks with different time zone. they all show same time. when i apply a change for a moment they show correct time then they all default to current time zone.
<img width="236" alt="Annotation 2020-07-31 222559" src="https://user-images.githubusercontent.com/8602381/89092177-7d03df80-d37d-11ea-8453-613d5d82947d.png">

card configuration:

`
cards:
  - disable_seconds: true
    show_city: true
    show_continent: true
    size: 150
    time_zone: America/Montreal
    type: 'custom:clock-card'
  - cards:
      - disable_seconds: true
        show_city: true
        size: 60
        time_zone: europe/amsterdam
        type: 'custom:clock-card'
      - disable_seconds: true
        show_city: true
        size: 60
        time_zone: europe/london
        type: 'custom:clock-card'
      - disable_seconds: true
        show_city: true
        size: 60
        time_zone: america/detroit
        type: 'custom:clock-card'
    type: horizontal-stack
  - entities:
      - entity: sensor.time_date
      - entity: sensor.time_utc
      - entity: sensor.internet_time
    show_icon: true
    show_name: true
    type: glance
type: vertical-stack
`

**Comment by Villhellm** [comment]
Newest release should fix this. I had misplaced a variable.
Thanks for the report!
