### ISSUE TITLE
Incorrect time shown

### ISSUE THREAD

**Issue by Gordontgopher** [Villhellm/lovelace-clock-card#5]
It appears that if the location is not recognised then local time is shown. Using the following config;
```   
      - type: "custom:clock-card"
        time_zone: "America/Concord"
        size: 200
        show_City: true
        show_continent: true
        disable_seconds: false
      - type: "custom:clock-card"
        time_zone: "England/London"
        size: 200
        show_city: true
        show_continent: true
        disable_seconds: false 
```

Gives this result:
![Screenshot 2020-08-01 at 11 08 27](https://user-images.githubusercontent.com/3321366/89099504-a9544600-d3e7-11ea-963d-448f357f1a8c.png)

But   
```   
      - type: "custom:clock-card"
        time_zone: "America/Chicago"
        size: 200
        show_City: true
        show_continent: true
        disable_seconds: false
      - type: "custom:clock-card"
        time_zone: "England/London"
        size: 200
        show_city: true
        show_continent: true
        disable_seconds: false
```

![Screenshot 2020-08-01 at 11 12 40](https://user-images.githubusercontent.com/3321366/89099530-f3d5c280-d3e7-11ea-87ec-690a686edc28.png)

(edited several times to try to get code tags to work!)
Also City doesn't appear in either case (probably a separate issue?)

**Comment by Villhellm** [comment]
That’s not a valid timezone, you have to pick a valid tz timezone https://en.m.wikipedia.org/wiki/List_of_tz_database_time_zones
I’ll add that to the readme later today

And you’ve capitalized “city” in your config, that’s why show_city isn’t working

**Comment by Gordontgopher** [comment]
OK that explains it :) 
I don't know how I managed to capitalise the city as I copied and pasted the first clock for the second, but I managed it!
