### ISSUE TITLE
Feature Request: Add option for a caption

### ISSUE THREAD

**Issue by Gordontgopher** [Villhellm/lovelace-clock-card#6]
Adding a caption (similar to show_city and show_continent) would cover a few scenarios, two obvious ones;

- Being able to refer to a location 'within' the time zone rather than the name of the time zone. For example UK has one timezone (London) but I may want to name the clock Manchester or whatever.

- Naming the location, rather than just showing the city. e.g. "US Office" or "Bob's House"

**Comment by Villhellm** [comment]
Added in the latest release. Thanks for the suggestion!
