### ISSUE TITLE
date doesn't change

### ISSUE THREAD

**Issue by ktownsend-personal** [Villhellm/lovelace-clock-card#9]
I added your clock to my wall tablet dashboards and noticed that the next day the date hasn't changed. I confirmed that on all devices. If they are continuously showing your clock across multiple days the date doesn't change from what it was when the page first loaded.

**Comment by Villhellm** [comment]
It works as far as I can tell https://i.imgur.com/XZVDWh4.gif
What is your current card config and what version of the card are you running?

**Comment by ktownsend-personal** [comment]
I'm running the latest version available on HACS. My tablet dashboards run 24x7 and usually don't need a page reload. I suspect the date is only rendering based on the initial date when the page loaded rather than re-rendering when the date changes.

```yaml
display_date: 'DDDD, MMMM D'
size: 218
type: 'custom:clock-card'
```

**Comment by ktownsend-personal** [comment]
I found the problem and created a pull request: https://github.com/Villhellm/lovelace-clock-card/pull/10
It only failed to change the date if there wasn't a caption.

**Comment by Villhellm** [comment]
thanks again!
